#!/bin/bash

# Sets the output path and filename of the generated ipset script.
outpath=/var/www/html
outfile=admin.ipt

# Sets the filename for the host/ip list.
list=/etc/iptadmin.lst

# Sets the path to the script on the client.
scriptpath=/tmp

# Sets the filename for the adminwhitelist ipset rules.
awlrules=/etc/iptables/adminwhitelist.rules

# (optional) Sets the filename for the IPTables rules/script files on the client.
# This will allow the script to replace the iptables rules with rules that implement ipset.
ip4rules=/etc/iptables/iptables.rules
ip6rules=/etc/iptables/ip6tables.rules

# Sets the address list timeout (in seconds) for the hosts in the host/ip list.
hosttimeout=14400

# List of secure ports (or IANA Service Names), comma-separated.  If firewall rules matching these ports are
# found when the script is run, ipset options will be applied to those rules.
secureports=ssh

# List of NMS Servers, comma-separated.  These hosts will not be deleted/reloaded when the script is run
# but will be checked and the timeout reset when run.  This prevents NMS Server dropouts during script reload.
# Hosts removed from this list will timeout (in seconds) when nmstimeout is reached.
nmsservers=nms.example.com,nms2.example.com
nmstimeout=86400

# Sets up the scheduler for fetching the iptadmin script.  The scripthost should be the path to the script on the host
# server. The scheduler will fetch scripthost/outfile (specified above).  Time is in minutes.
scripthost=https://www.example.com
schedtime=5

# Enable/Disable the Failsafe Script (optional). This removes the ipset option from port 22 after a set timeout,
# should the script fail to fetch/run from the host server. Timeout is reset to failtime every script fetch/run.
failsafe=true
failtime=72h

function ip4address () {
 if [[ $1 =~ ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)((\/([8-9]|[1-2][0-9]|3[1-2]))?)$ ]]; then
 ipv4addr=$1; else ipv4addr=$(dig A +short $1 | grep -v "\.$" | xargs -rn1); fi
}

function ip6address () {
 if [[ $1 =~ ^(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}|(?=(?:[a-fA-F0-9]{0,4}:){0,7}[a-fA-F0-9]{0,4})(([a-fA-F0-9]{1,4}:){1,7}|:)((:[a-fA-F0-9]{1,4}){1,7}|:)((\/([1-9]|[1-9][0-9]|1[01][0-9]|12[0-7]))?)$ ]]; then
 ipv6addr=$1; else ipv6addr=$(dig AAAA +short $1 | grep -v "\.$" | xargs -rn1); fi
}

function nmstimeout () {
 if [ $nmstimeout ]; then printf ' timeout '"$nmstimeout"; else printf ''; fi
}

function hosttimeout () {
 if [ $hosttimeout ]; then printf ' timeout '"$hosttimeout"; else printf ''; fi
}

function iptdate () { printf "$(TZ=EST5EDT date '+%b/%d/%Y')"; }

function ipttime () { printf "$(TZ=EST5EDT date '+%H:%M:%S')"; }

script=$outpath/$outfile

printf "#!/bin/bash
# Generated on $(date)
printf 'create -exist admin hash:net$(hosttimeout) family inet
create -exist admin6 hash:net$(hosttimeout) family inet6\n' | tee $awlrules
" | tee $script &> /dev/null

if [ $nmsservers ]; then
 for server in $(printf $nmsservers | tr "," " "); do
  ip4address $server
  if [ $ipv4addr ]; then
   printf "printf 'add -exist admin $ipv4addr$(nmstimeout)\\\n' | tee -a $awlrules\n" | tee -a $script &> /dev/null
  fi
 done
fi

while read hostlist; do
  ip4address $hostlist
  if [ $ipv4addr ]; then
   printf "printf 'add -exist admin $ipv4addr$(hosttimeout)\\\n' | tee -a $awlrules\n" | tee -a $script &> /dev/null
  fi
done <$list

if [ $ip4rules ]; then
 for port in $(echo $secureports | tr "," " "); do
  printf "sed -i '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin src -j ACCEPT' $ip4rules
" | tee -a $script &> /dev/null
 done
fi

if [ $nmsservers ]; then
 for server in $(printf $nmsservers | tr "," " "); do
  ip6address $server
  if [ $ipv6addr ]; then
   printf "printf 'add -exist admin6 $ipv6addr$(nmstimeout)\\\n' | tee -a $awlrules\n" | tee -a $script &> /dev/null
  fi
 done
fi

while read hostlist; do
  ip6address $hostlist
  if [ $ipv6addr ]; then
   printf "printf 'add -exist admin6 $ipv6addr$(hosttimeout)\\\n' | tee -a $awlrules\n" | tee -a $script &> /dev/null
  fi
done <$list

if [ $ip6rules ]; then
 for port in $(echo $secureports | tr "," " "); do
  printf "sed -i '/$port/c\-A INPUT -p tcp -m state --state NEW --dport $port -m set --match-set admin6 src -j ACCEPT' $ip6rules
" | tee -a $script &> /dev/null
 done
fi

printf "/sbin/ipset restore -f $awlrules\n" | tee -a $script &> /dev/null

printf "if [ ! -f /etc/systemd/system/adminwhitelistipu.service ] || [ ! -f /etc/systemd/system/adminwhitelistipu.timer ]; then
printf '[Unit]
Description=adminwhitelist update
[Service]
Type=simple
ExecStart=/bin/sh 'curl -ks $scripthost/$outfile > $scriptpath/$outfile && sh $scriptpath/$outfile'
[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/adminwhitelistipu.service
printf '[Unit]
Description=adminwhitelist update scheduler
[Timer]
OnCalendar=*:0/5
Unit=adminwhitelist.service
[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/adminwhitelistipu.timer
systemctl daemon-reload
systemctl enable adminwhitelistipu.timer
fi
if [ ! -f /etc/systemd/system/adminwhitelist.service ]; then
printf '[Unit]
Description=Packet Filtering Framework
[Service]
Type=simple
ExecStart=/sbin/ipset restore -f $awlrules
ExecReload=/sbin/ipset restore -f $awlrules
[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/adminwhitelist.service
systemctl daemon-reload
systemctl enable adminwhitelist.service
fi\n" | tee -a $script &> /dev/null

if [ $failsafe == true ]; then
printf "if [ ! -f $scriptpath/awfailsafe ]; then
printf '#!/bin/bash
ipset -exist add admin 0.0.0.0/0
ipset -exist add admin6 ::/0\n' >> $scriptpath/awfailsafe.ipt
fi\n" | tee -a $script &> /dev/null
printf "if [ "'$(systemctl is-active awfailsafe.timer)'" != 'active' ]; then
 systemd-run --on-active=$failtime --unit awfailsafe.service sh $scriptpath/awfailsafe.ipt
else
 systemctl restart awfailsafe.timer
fi\n" | tee -a $script &> /dev/null
fi
