#!/bin/bash

printf '[Unit]
Description=IPTables Admin Whitelist Creator
[Service]
Type=simple
ExecStart=/usr/local/bin/iptadmin
[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/iptadmin.service

printf '[Unit]
Description=IPTables Admin Whitelist Scheduler
[Timer]
OnCalendar=*:0/5
Unit=iptadmin.service
[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/iptadmin.timer

systemctl daemon-reload
systemctl enable iptadmin.timer